; PlatformIO Project Configuration File
[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

lib_ldf_mode = chain+ 

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit TouchScreen
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    prenticedavid/MCUFRIEND_kbv